import 'package:flutter/material.dart';

const labelTextStyle = TextStyle(
  fontSize: 18.0,
  color: Color(0xFF8D8E98),
);

class IconContent extends StatelessWidget {
  // This constructor is generated by the system. Key allows for tracking the Widget instance.
  //  const IconContent({
  //    Key key,
  //  }) : super(key: key);

  IconContent({@required this.displayIcon, @required this.displayText});

  final IconData displayIcon;
  final String displayText;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Icon(
          displayIcon,
          size: 80.0,
        ),
        SizedBox(
          // spacer
          height: 15.0,
        ),
        Text(
          displayText,
          style: labelTextStyle,
        ),
      ],
    );
  }
}